local addonName, Addon = ...

Addon.name = addonName
Addon.version = "0.5.0"

local deDE = {
    ADDON_DESCRIPTION = "Halte die Taste gedrückt, wähle mit der Maus ein Emote und lasse die Taste los.",
    OPTIONS_TITLE = "EmoteRing",
    OPTIONS_SUBTITLE = "Schnelle Emotes für Begegnungen in der offenen Welt",
    KEYBIND_TITLE = "Tastenbelegung",
    KEYBIND_HINT = "Diese Taste gedrückt halten, um den Ring zu öffnen.",
    NOT_BOUND = "Nicht belegt",
    SET_KEY = "Taste festlegen",
    PRESS_KEY = "Gewünschte Taste drücken",
    PRESS_KEY_HINT = "Escape bricht ab. Maustasten können ebenfalls verwendet werden.",
    PRESS_KEY_UMLAUT_HINT = "Hinweis: Umlaut-/Sondertasten (ü, ö, ä, ß) funktionieren clientbedingt nicht zuverlässig als Tastenbelegung. Bitte einen Buchstaben, eine Zahl, eine F-Taste oder eine Modifikator-Kombination (z. B. ALT-K) verwenden.",
    BINDING_CONFLICT = "%s ist bereits mit „%s“ belegt. Wirklich ersetzen?",
    SLOT_TITLE = "Emotes im Ring",
    SLOT_HINT = "Jeder Platz entspricht einem Segment des Rings. Platz 1 liegt oben, danach geht es im Uhrzeigersinn weiter.",
    SLOT = "Platz %d",
    CHANGE = "Ändern",
    MOVE_LEFT = "Nach links",
    MOVE_RIGHT = "Nach rechts",
    LAYOUTS_TITLE = "Layouts",
    LAYOUT_HINT = "Bis zu vier Ringe. Wähle im geöffneten Ring einen kleinen Innenkreis, um das Layout zu wechseln.",
    LAYOUT_NAME = "Name",
    DEFAULT_LAYOUT = "Beim Öffnen verwenden",
    LAYOUT_SOCIAL = "Begegnung",
    LAYOUT_ROLEPLAY = "Rollenspiel",
    LAYOUT_REACTIONS = "Reaktionen",
    LAYOUT_GROUP = "Gruppe",
    GENERAL_TITLE = "Verhalten und Darstellung",
    PREFER_MOUSEOVER = "Spieler oder NPC unter der Maus bevorzugen",
    PREFER_MOUSEOVER_TOOLTIP = "Mouseover wird beim Öffnen kurz als Ziel gesichert und nach dem Emote wieder auf dein vorheriges Ziel zurückgestellt. Im Kampf wird die sichere Unit-Token-Suche verwendet.",
    SHOW_TARGET = "Gespeichertes Ziel unter dem Ring anzeigen",
    PLAY_SOUNDS = "Dezente WoW-Sounds verwenden",
    SHOW_MINIMAP = "Minimap-Button anzeigen",
    RING_SCALE = "Größe des Rings",
    RESET = "Standard wiederherstellen",
    RESET_CONFIRM = "Alle Einstellungen und Ringplätze auf den Standard zurücksetzen?",
    PICKER_TITLE = "Emote auswählen",
    SEARCH = "Emote suchen …",
    CLOSE = "Schließen",
    TARGET = "Ziel: %s",
    NO_TARGET = "Ohne Ziel",
    CANCEL = "Abbrechen",
    STATUS = "Status",
    CATEGORY_SOCIAL = "Sozial",
    CATEGORY_REACTION = "Reaktionen",
    CATEGORY_ROLEPLAY = "Rollenspiel",
    CATEGORY_GROUP = "Gruppe",
    CATEGORY_STATUS = "Status",
    CATEGORY_OTHER = "Weitere",
    CATEGORY_ALL = "Alle",
    PICKER_COUNT = "%d Emotes",
    BINDING_SAVED = "Taste gespeichert: %s",
    BINDING_COMBAT = "Die Tastenbelegung kann während des Kampfes nicht geändert werden.",
    BINDING_MIGRATED = "Die alte Tastenbelegung wurde sicher aktualisiert. Bitte die Taste noch einmal drücken.",
    OPEN_OPTIONS = "Optionen öffnen",
    MINIMAP_TOOLTIP = "Linksklick: Optionen\nRechtsklick: Ring-Vorschau\nZiehen: Position ändern",
}

local enUS = {
    ADDON_DESCRIPTION = "Hold the key, choose an emote with the mouse, then release the key.",
    OPTIONS_TITLE = "EmoteRing",
    OPTIONS_SUBTITLE = "Quick emotes for meeting others in the open world",
    KEYBIND_TITLE = "Key binding",
    KEYBIND_HINT = "Hold this key to open the ring.",
    NOT_BOUND = "Not bound",
    SET_KEY = "Set key",
    PRESS_KEY = "Press the desired key",
    PRESS_KEY_HINT = "Escape cancels. Mouse buttons can also be used.",
    PRESS_KEY_UMLAUT_HINT = "Note: Umlaut/special keys (ü, ö, ä, ß) are not reliably usable as key bindings due to client limitations. Please use a letter, number, function key, or modifier combination (e.g. ALT-K) instead.",
    BINDING_CONFLICT = "%s is already bound to “%s”. Replace it?",
    SLOT_TITLE = "Emotes on the ring",
    SLOT_HINT = "Each slot is one ring segment. Slot 1 is at the top; the rest continue clockwise.",
    SLOT = "Slot %d",
    CHANGE = "Change",
    MOVE_LEFT = "Move left",
    MOVE_RIGHT = "Move right",
    LAYOUTS_TITLE = "Layouts",
    LAYOUT_HINT = "Up to four rings. Choose a small inner circle while the ring is open to switch layout.",
    LAYOUT_NAME = "Name",
    DEFAULT_LAYOUT = "Use when opening",
    LAYOUT_SOCIAL = "Meeting",
    LAYOUT_ROLEPLAY = "Roleplay",
    LAYOUT_REACTIONS = "Reactions",
    LAYOUT_GROUP = "Group",
    GENERAL_TITLE = "Behavior and appearance",
    PREFER_MOUSEOVER = "Prefer the player or NPC under the mouse",
    PREFER_MOUSEOVER_TOOLTIP = "Mouseover is temporarily secured as the target when the ring opens and your previous target is restored after the emote. In combat, safe unit-token lookup is used.",
    SHOW_TARGET = "Show the saved target below the ring",
    PLAY_SOUNDS = "Use subtle WoW sounds",
    SHOW_MINIMAP = "Show minimap button",
    RING_SCALE = "Ring size",
    RESET = "Restore defaults",
    RESET_CONFIRM = "Reset all settings and ring slots to their defaults?",
    PICKER_TITLE = "Choose an emote",
    SEARCH = "Search emotes …",
    CLOSE = "Close",
    TARGET = "Target: %s",
    NO_TARGET = "No target",
    CANCEL = "Cancel",
    STATUS = "Status",
    CATEGORY_SOCIAL = "Social",
    CATEGORY_REACTION = "Reactions",
    CATEGORY_ROLEPLAY = "Roleplay",
    CATEGORY_GROUP = "Group",
    CATEGORY_STATUS = "Status",
    CATEGORY_OTHER = "More",
    CATEGORY_ALL = "All",
    PICKER_COUNT = "%d emotes",
    BINDING_SAVED = "Key saved: %s",
    BINDING_COMBAT = "The key binding cannot be changed during combat.",
    BINDING_MIGRATED = "The old key binding was updated securely. Please press the key once more.",
    OPEN_OPTIONS = "Open options",
    MINIMAP_TOOLTIP = "Left-click: Options\nRight-click: Ring preview\nDrag: Move",
}

Addon.L = GetLocale() == "deDE" and deDE or enUS

local labelsDE = {
    HELLO = "Hallo",
    WAVE = "Winken",
    BYE = "Tschüss",
    WELCOME = "Willkommen",
    THANK = "Danke",
    PLEAD = "Bitte",
    APOLOGIZE = "Entschuldigen",
    BOW = "Verbeugen",
    SALUTE = "Salutieren",
    NOD = "Nicken",
    NO = "Nein",
    CHEER = "Jubeln",
    APPLAUD = "Applaudieren",
    CONGRATULATE = "Gratulieren",
    LAUGH = "Lachen",
    CRY = "Weinen",
    SIGH = "Seufzen",
    SHRUG = "Schulterzucken",
    GASP = "Staunen",
    ANGRY = "Wütend",
    SMILE = "Lächeln",
    BLUSH = "Erröten",
    HUG = "Umarmen",
    KISS = "Küssen",
    POINT = "Zeigen",
    PONDER = "Nachdenken",
    DANCE = "Tanzen",
    SIT = "Hinsetzen",
    KNEEL = "Knien",
    SLEEP = "Schlafen",
    FLEX = "Muskeln zeigen",
    ROAR = "Brüllen",
    WAIT = "Warten",
    FOLLOW = "Folgt mir",
    HELPME = "Hilfe",
    FLEE = "Fliehen",
    CHARGE = "Angreifen",
    OOM = "Kein Mana",
    HEALME = "Heilt mich",
    AFK = "AFK an/aus",
    DND = "Nicht stören an/aus",
}

local labelsEN = {
    HELLO = "Hello",
    WAVE = "Wave",
    BYE = "Goodbye",
    WELCOME = "Welcome",
    THANK = "Thank",
    PLEAD = "Please",
    APOLOGIZE = "Apologize",
    BOW = "Bow",
    SALUTE = "Salute",
    NOD = "Nod",
    NO = "No",
    CHEER = "Cheer",
    APPLAUD = "Applaud",
    CONGRATULATE = "Congratulate",
    LAUGH = "Laugh",
    CRY = "Cry",
    SIGH = "Sigh",
    SHRUG = "Shrug",
    GASP = "Gasp",
    ANGRY = "Angry",
    SMILE = "Smile",
    BLUSH = "Blush",
    HUG = "Hug",
    KISS = "Kiss",
    POINT = "Point",
    PONDER = "Ponder",
    DANCE = "Dance",
    SIT = "Sit",
    KNEEL = "Kneel",
    SLEEP = "Sleep",
    FLEX = "Flex",
    ROAR = "Roar",
    WAIT = "Wait",
    FOLLOW = "Follow me",
    HELPME = "Help",
    FLEE = "Flee",
    CHARGE = "Charge",
    OOM = "Out of mana",
    HEALME = "Heal me",
    AFK = "Toggle AFK",
    DND = "Toggle DND",
}

local labels = GetLocale() == "deDE" and labelsDE or labelsEN

local ICON = "Interface\\Icons\\"

Addon.catalog = {
    { id = "HELLO", token = "HELLO", label = labels.HELLO, category = "CATEGORY_SOCIAL", icon = ICON .. "Achievement_Character_Human_Female" },
    { id = "WAVE", token = "WAVE", label = labels.WAVE, category = "CATEGORY_SOCIAL", icon = ICON .. "Ability_Monk_TigerPalm" },
    { id = "BYE", token = "BYE", label = labels.BYE, category = "CATEGORY_SOCIAL", icon = ICON .. "Ability_Rogue_Sprint" },
    { id = "WELCOME", token = "WELCOME", label = labels.WELCOME, category = "CATEGORY_SOCIAL", icon = ICON .. "Achievement_Character_Human_Female" },
    { id = "THANK", token = "THANK", label = labels.THANK, category = "CATEGORY_SOCIAL", icon = ICON .. "Spell_Holy_HopeAndGrace" },
    { id = "PLEAD", token = "PLEAD", label = labels.PLEAD, category = "CATEGORY_SOCIAL", icon = ICON .. "Spell_Holy_PrayerOfHealing" },
    { id = "APOLOGIZE", token = "APOLOGIZE", label = labels.APOLOGIZE, category = "CATEGORY_SOCIAL", icon = ICON .. "Spell_Holy_Restoration" },
    { id = "BOW", token = "BOW", label = labels.BOW, category = "CATEGORY_SOCIAL", icon = ICON .. "Ability_Hunter_FocusedAim" },
    { id = "SALUTE", token = "SALUTE", label = labels.SALUTE, category = "CATEGORY_SOCIAL", icon = ICON .. "Ability_Warrior_CommandingShout" },
    { id = "NOD", token = "NOD", label = labels.NOD, category = "CATEGORY_SOCIAL", icon = ICON .. "INV_Misc_Note_01" },
    { id = "NO", token = "NO", label = labels.NO, category = "CATEGORY_REACTION", icon = ICON .. "Spell_Shadow_SealOfKings" },
    { id = "CHEER", token = "CHEER", label = labels.CHEER, category = "CATEGORY_REACTION", icon = ICON .. "Achievement_BG_WinWSG" },
    { id = "APPLAUD", token = "APPLAUD", label = labels.APPLAUD, category = "CATEGORY_REACTION", icon = ICON .. "Ability_Monk_TigerPalm" },
    { id = "CONGRATULATE", token = "CONGRATULATE", label = labels.CONGRATULATE, category = "CATEGORY_REACTION", icon = ICON .. "Achievement_General" },
    { id = "LAUGH", token = "LAUGH", label = labels.LAUGH, category = "CATEGORY_REACTION", icon = ICON .. "Ability_Racial_Cannibalize" },
    { id = "CRY", token = "CRY", label = labels.CRY, category = "CATEGORY_REACTION", icon = ICON .. "Spell_Shadow_MindSteal" },
    { id = "SIGH", token = "SIGH", label = labels.SIGH, category = "CATEGORY_REACTION", icon = ICON .. "Spell_Shadow_MindTwisting" },
    { id = "SHRUG", token = "SHRUG", label = labels.SHRUG, category = "CATEGORY_REACTION", icon = ICON .. "INV_Misc_QuestionMark" },
    { id = "GASP", token = "GASP", label = labels.GASP, category = "CATEGORY_REACTION", icon = ICON .. "Spell_Shadow_Possession" },
    { id = "ANGRY", token = "ANGRY", label = labels.ANGRY, category = "CATEGORY_REACTION", icon = ICON .. "Ability_Warrior_Rampage" },
    { id = "SMILE", token = "SMILE", label = labels.SMILE, category = "CATEGORY_REACTION", icon = ICON .. "Spell_Holy_SealOfWisdom" },
    { id = "BLUSH", token = "BLUSH", label = labels.BLUSH, category = "CATEGORY_REACTION", icon = ICON .. "INV_ValentinesCard01" },
    { id = "HUG", token = "HUG", label = labels.HUG, category = "CATEGORY_SOCIAL", icon = ICON .. "Spell_Holy_DevotionAura" },
    { id = "KISS", token = "KISS", label = labels.KISS, category = "CATEGORY_SOCIAL", icon = ICON .. "INV_ValentinesCard02" },
    { id = "POINT", token = "POINT", label = labels.POINT, category = "CATEGORY_ROLEPLAY", icon = ICON .. "Ability_Hunter_MarkedForDeath" },
    { id = "PONDER", token = "PONDER", label = labels.PONDER, category = "CATEGORY_ROLEPLAY", icon = ICON .. "INV_Misc_Book_09" },
    { id = "DANCE", token = "DANCE", label = labels.DANCE, category = "CATEGORY_ROLEPLAY", icon = ICON .. "Achievement_Brewery_2" },
    { id = "SIT", token = "SIT", label = labels.SIT, category = "CATEGORY_ROLEPLAY", icon = ICON .. "INV_Misc_Coin_01" },
    { id = "KNEEL", token = "KNEEL", label = labels.KNEEL, category = "CATEGORY_ROLEPLAY", icon = ICON .. "Spell_Holy_PrayerOfMending" },
    { id = "SLEEP", token = "SLEEP", label = labels.SLEEP, category = "CATEGORY_ROLEPLAY", icon = ICON .. "Spell_Nature_Sleep" },
    { id = "FLEX", token = "FLEX", label = labels.FLEX, category = "CATEGORY_ROLEPLAY", icon = ICON .. "Ability_Warrior_BloodFrenzy" },
    { id = "ROAR", token = "ROAR", label = labels.ROAR, category = "CATEGORY_ROLEPLAY", icon = ICON .. "Ability_Druid_ChallangingRoar" },
    { id = "WAIT", token = "WAIT", label = labels.WAIT, category = "CATEGORY_GROUP", icon = ICON .. "INV_Misc_PocketWatch_01" },
    { id = "FOLLOW", token = "FOLLOW", label = labels.FOLLOW, category = "CATEGORY_GROUP", icon = ICON .. "Ability_Hunter_SniperShot" },
    { id = "HELPME", token = "HELPME", label = labels.HELPME, category = "CATEGORY_GROUP", icon = ICON .. "Spell_Holy_SealOfSacrifice" },
    { id = "FLEE", token = "FLEE", label = labels.FLEE, category = "CATEGORY_GROUP", icon = ICON .. "Ability_Rogue_Sprint" },
    { id = "CHARGE", token = "CHARGE", label = labels.CHARGE, category = "CATEGORY_GROUP", icon = ICON .. "Ability_Warrior_Charge" },
    { id = "OOM", token = "OOM", label = labels.OOM, category = "CATEGORY_GROUP", icon = ICON .. "Spell_Shadow_ManaBurn" },
    { id = "HEALME", token = "HEALME", label = labels.HEALME, category = "CATEGORY_GROUP", icon = ICON .. "Spell_Holy_Heal" },
    { id = "AFK", action = "AFK", label = labels.AFK, category = "CATEGORY_STATUS", icon = ICON .. "Spell_Nature_Sleep" },
    { id = "DND", action = "DND", label = labels.DND, category = "CATEGORY_STATUS", icon = ICON .. "Spell_Shadow_AntiMagicShell" },
}

Addon.catalogByID = {}
for _, entry in ipairs(Addon.catalog) do
    Addon.catalogByID[entry.id] = entry
end

-- Retail publishes its standard emotes as EMOTE<n>_TOKEN globals. Curated
-- entries above keep useful names, categories and icons; everything else is
-- appended automatically so the picker follows the installed game client.
for index = 1, 1200 do
    local token = _G["EMOTE" .. index .. "_TOKEN"]
    if type(token) == "string" and token ~= "" and not Addon.catalogByID[token] then
        local command = _G["EMOTE" .. index .. "_CMD1"]
        local label = type(command) == "string" and command or token
        label = label:gsub("^/", ""):gsub("_", " ")
        label = label:gsub("^%l", string.upper)

        local entry = {
            id = token,
            token = token,
            label = label,
            category = "CATEGORY_OTHER",
            icon = ICON .. "INV_Misc_Note_01",
            discovered = true,
        }
        Addon.catalog[#Addon.catalog + 1] = entry
        Addon.catalogByID[token] = entry
    end
end

Addon.defaults = {
    schemaVersion = 2,
    layouts = {
        {
            name = Addon.L.LAYOUT_SOCIAL,
            slots = { "HELLO", "WAVE", "THANK", "PLEAD", "APOLOGIZE", "BOW", "CHEER", "BYE" },
        },
        {
            name = Addon.L.LAYOUT_ROLEPLAY,
            slots = { "BOW", "SALUTE", "POINT", "PONDER", "DANCE", "SIT", "KNEEL", "SLEEP" },
        },
        {
            name = Addon.L.LAYOUT_REACTIONS,
            slots = { "NOD", "NO", "LAUGH", "CRY", "SIGH", "SHRUG", "GASP", "ANGRY" },
        },
        {
            name = Addon.L.LAYOUT_GROUP,
            slots = { "WAIT", "FOLLOW", "HELPME", "FLEE", "CHARGE", "OOM", "HEALME", "CHEER" },
        },
    },
    defaultLayout = 1,
    preferMouseover = true,
    showTarget = true,
    playSounds = true,
    showMinimap = true,
    minimapAngle = 220,
    ringScale = 1.0,
}

BINDING_HEADER_EMOTERING = "EmoteRing"
BINDING_NAME_EMOTERING_OPEN = GetLocale() == "deDE" and "Emote-Ring öffnen (halten)" or "Open Emote Ring (hold)"
